# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170514_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.AddField(
            model_name='record',
            name='attachments',
            field=models.ManyToManyField(related_name='records', to='main.Attachment'),
        ),
    ]
